language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  - cypress install
before_script:
  - yarn build
  - yarn start --silent &
script:
  - yarn testCI
  - $(npm bin)/cypress run --record