language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - yarn build
  - yarn start --silent &
script:
  - yarn tests
  - $(npm bin)/cypress run --record